### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Anonyfox** [gjaldon/ectophile#7]
Hi! 

I implemented your module (v0.3.0) inside a new phoenix app, following the steps in your README. 

First: seems that this required step is missing from your doc: you have to put this in your config/config.ex: `config :ectophile, otp_app: :your_app_name`. 

Second: running on elixir 1.0, phoenix 1.0 and sqlite this shows up when I try to submit a form: 

Request: POST /recipes/4
*\* (exit) an exception was raised:
    *\* (Protocol.UndefinedError) protocol Access not implemented for "{\"filepath\":\"/priv/static/image/uploads/b3793d6513bc22b34b53fc311d7b97.jpeg\",\"filename\":\"Cells.jpeg\"}" 
        (elixir) lib/access.ex:1: Access.impl_for!/1
        (elixir) lib/access.ex:33: Access.get/2
        (ectophile) lib/ectophile.ex:51: Ectophile.rm_file/2 
        (hoppelkochbuch) web/models/recipe.ex:1: Hoppelkochbuch.Recipe.before_update/1
        (ecto) lib/ecto/model/callbacks.ex:315: Ecto.Model.Callbacks.**apply**/3
        (ecto) lib/ecto/repo/model.ex:139: anonymous fn/10 in Ecto.Repo.Model.do_update/4
        (ecto) lib/ecto/repo/model.ex:396: anonymous fn/3 in Ecto.Repo.Model.wrap_in_transaction/8
        (ecto) lib/ecto/pool.ex:292: Ecto.Pool.with_rollback/3
        (ecto) lib/ecto/adapters/sql.ex:579: Ecto.Adapters.SQL.transaction/8
        (ecto) lib/ecto/pool.ex:244: Ecto.Pool.outer_transaction/6

**Comment by gjaldon** [comment]
@Anonyfox - looks like the problem may be with the `sqlite` adapter. It did not parse the JSON into an Elixir map. Did you set `:map` as type of the field? I'll mention the required `:otp_app` to the docs.
